-- MySQL Script generated by MySQL Workbench
-- Sat Apr 29 20:02:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema biddingschema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biddingschema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biddingschema` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `phone_no` VARCHAR(12) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `phone_no_UNIQUE` (`phone_no` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacts` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `img_path` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone_no`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone_no` (
  `id` INT NOT NULL COMMENT '	',
  `phone_no` VARCHAR(45) NOT NULL COMMENT '	',
  `type` VARCHAR(45) NOT NULL,
  `contacts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phone_no_contacts_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_phone_no_contacts`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `mydb`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`email` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `contacts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_email_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `mydb`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `idaddress` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `contacts_id` INT NOT NULL,
  PRIMARY KEY (`idaddress`),
  INDEX `fk_address_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_address_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `mydb`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_contact` (
  `users_id` INT NOT NULL,
  `contacts_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `contacts_id`, `groups_id`),
  INDEX `fk_user_has_contact_contacts1_idx` (`contacts_id` ASC),
  INDEX `fk_user_has_contact_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_user_has_contact_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_contact_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `mydb`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_contact_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `mydb`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `biddingschema` ;

-- -----------------------------------------------------
-- Table `biddingschema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `mobile` VARCHAR(45) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `registration_date` DATE NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biddingschema`.`buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`buyer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(150) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_buyer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_buyer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `biddingschema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biddingschema`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`seller` (
  `id` INT(11) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_user_idx` (`id` ASC),
  CONSTRAINT `fk_email_user`
    FOREIGN KEY (`id`)
    REFERENCES `biddingschema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biddingschema`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  `manufacturing_name` VARCHAR(100) NOT NULL,
  `manufacturing_date` DATE NOT NULL,
  `expiration_date` DATE NULL DEFAULT NULL,
  `seller_id` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NOT NULL,
  `offered_date` DATE NOT NULL,
  `finish_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_seller1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_product_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `biddingschema`.`seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biddingschema`.`buyer_bid_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`buyer_bid_product` (
  `buyer_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `amount` FLOAT NOT NULL,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`buyer_id`, `product_id`),
  INDEX `fk_buyer_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_buyer_has_product_buyer1_idx` (`buyer_id` ASC),
  CONSTRAINT `fk_buyer_has_product_buyer1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `biddingschema`.`buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buyer_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `biddingschema`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biddingschema`.`buyer_buy_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`buyer_buy_product` (
  `buyer_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` FLOAT NOT NULL,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`buyer_id`, `product_id`),
  INDEX `fk_buyer_has_product_product2_idx` (`product_id` ASC),
  INDEX `fk_buyer_has_product_buyer2_idx` (`buyer_id` ASC),
  CONSTRAINT `fk_buyer_has_product_buyer2`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `biddingschema`.`buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buyer_has_product_product2`
    FOREIGN KEY (`product_id`)
    REFERENCES `biddingschema`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biddingschema`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biddingschema`.`product_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biddingschema`.`product_has_category` (
  `product_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_product_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_product_has_category_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `biddingschema`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `biddingschema`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
