-- MySQL Script generated by MySQL Workbench
-- Sun Apr 30 11:08:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Contactx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Contactx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Contactx` DEFAULT CHARACTER SET utf8 ;
USE `Contactx` ;

-- -----------------------------------------------------
-- Table `Contactx`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contactx`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_no` VARCHAR(12) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `phone_no_UNIQUE` (`phone_no` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contactx`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contactx`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contactx`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contactx`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `img_path` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contactx`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contactx`.`phone` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `phone_no` VARCHAR(45) NOT NULL COMMENT '	',
  `type` VARCHAR(45) NOT NULL,
  `contacts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phone_no_contacts_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_phone_no_contacts`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `Contactx`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contactx`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contactx`.`email` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `contacts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_email_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `Contactx`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contactx`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contactx`.`address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `contacts_id` INT NOT NULL,
  PRIMARY KEY (`idaddress`),
  INDEX `fk_address_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_address_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `Contactx`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contactx`.`user_has_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contactx`.`user_has_contact` (
  `users_id` INT NOT NULL,
  `contacts_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `contacts_id`, `groups_id`),
  INDEX `fk_user_has_contact_contacts1_idx` (`contacts_id` ASC),
  INDEX `fk_user_has_contact_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_user_has_contact_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Contactx`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_contact_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `Contactx`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_contact_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `Contactx`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
